import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { Row, Col, Card, Button } from 'react-bootstrap'

const Home: NextPage = () => {

  const router = useRouter()

  const onGetStarted = () => {
    router.push('/my-lists')
  }

  return (
    <div className='d-flex flex-column'>
      <Head>
        <title>List Simple</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <h1 className='mt-5 text-center'>List Simple</h1>
      <div className='text-center mb-4 fs-5'>An online tool to help you keep track of the important things in your life.</div>
      <Button className='mb-5 col-3 align-self-center' variant='primary' onClick={onGetStarted}>Get Started</Button>

      <section className='mt-4'>

        <Row className="g-5 justify-content-md-between justify-content-center">

            <Col xs={8} md={3}>
              <Card className='border-0'>
                <Image src='/contract.png' alt='' layout='responsive' height='100%' width='100%'></Image>
                <Card.Body className='p-0 mt-3'>
                  <Card.Title>1. Sign up / Login</Card.Title>
                  <Card.Text>
                    This is a longer card with supporting text below as a natural
                    lead-in to additional content. This content is a little bit
                    longer.
                  </Card.Text>
                </Card.Body>
              </Card>
            </Col>

            <Col xs={8} md={3}>
              <Card className='border-0'>
                <Image className='me-2' src='/list-svgrepo-com.svg' alt='' layout='responsive' height='100%' width='100%'></Image>
                <Card.Body className='p-0 mt-3'>
                  <Card.Title>2. Create Lists</Card.Title>
                  <Card.Text>
                    This is a longer card with supporting text below as a natural
                    lead-in to additional content. This content is a little bit
                    longer.
                  </Card.Text>
                </Card.Body>
              </Card>
            </Col>

            <Col xs={8} md={3} className="mb-5 mb-md-0">
              <Card className='border-0'>
                <Image className='' src='/diskette-save-svgrepo-com.svg' alt='' layout='responsive' height='100%' width='100%'></Image>
                <Card.Body className='p-0 mt-3'>
                  <Card.Title>3. Save Lists</Card.Title>
                  <Card.Text>
                    This is a longer card with supporting text below as a natural
                    lead-in to additional content. This content is a little bit
                    longer.
                  </Card.Text>
                </Card.Body>
              </Card>
            </Col>
        </Row>

      </section>

    </div>
  )
}

export default Home
