import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>List Simple</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <h1 className='mt-5 text-center'>List Simple</h1>
      <div className='text-center'>A simple online tool to help you keep track of the important things in your life.</div>

    </div>
  )
}

export default Home
